# Generated by Django 4.2.5 on 2023-10-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='is_participated',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Description', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='face_encoding',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
