# Generated by Django 4.2.5 on 2023-10-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_remove_participation_is_participated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
