# Generated by Django 4.2.5 on 2023-10-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(unique_for_date=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='date',
            field=models.DateField(unique_for_date=True),
        ),
    ]
